theme: jekyll-theme-tactile

title: "Dean's Blog"
description: >
  I am a student at Michigan Technological University studying Computer Science.

permalink: /:year-:title/
paginate: 5
gems:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile
