theme: jekyll-theme-tactile

title: "Dean's Blog"
description: >
  I am a student at Michigan Technological University studying Computer Science.
  Check out my <a href="https://www.deanveloper.com">main website</a>

permalink: /:year-:title/
paginate: 5
gems:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile
